/**
 * Created by lonelydawn on 2017-11-20.
 */

export const OUTPUT_SET_COLLEGE = 'OUTPUT_SET_COLLEGE'
export const OUTPUT_SET_TARGET = 'OUTPUT_SET_TARGET'
export const OUTPUT_SET_TABLE = 'OUTPUT_SET_TABLE'
export const OUTPUT_SET_SCORE = 'OUTPUT_SET_TARGET'
export const OUTPUT_SET_STAFF = 'OUTPUT_SET_TABLE'
export const OUTPUT_SET_TREE = 'OUTPUT_SET_TREE'
export const OUTPUT_SET_TREE_SCORE = 'OUTPUT_SET_TREE_SCORE'
export const COMPLETION_SET_COMPLETION = 'COMPLETION_SET_COMPLETION'
export const COMPLETION_SET_TARGET = 'COMPLETION_SET_TARGET'
export const COMPLETION_SET_COLLEGE = 'COMPLETION_SET_COLLEGE'
export const COMPLETION_SET_TARGET_TREE = 'COMPLETION_SET_TARGET_TREE'
export const COMPLETION_SET_COLLEGE_TREE = 'COMPLETION_SET_COLLEGE_TREE'
export const COMPLETION_SET_MENU_TREE = 'COMPLETION_SET_MENU_TREE'
export const COMPLETION_SET_TARGET_DATA = 'COMPLETION_SET_TARGET_DATA'
export const COMPLETION_SET_COLLEGE_DATA = 'COMPLETION_SET_COLLEGE_DATA'
export const OUTPUT_INPUT_SET_TARGET = 'OUTPUT_INPUT_SET_TARGET'
export const OUTPUT_INPUT_SET_COLLEGE = 'OUTPUT_INPUT_SET_COLLEGE'
export const OUTPUT_INPUT_SET_TABLE = 'OUTPUT_INPUT_SET_TABLE'
